// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: rag.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RAGIndexSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	CharacterDir  string                 `protobuf:"bytes,2,opt,name=character_dir,json=characterDir,proto3" json:"character_dir,omitempty"`
	SourceId      string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	SourceType    string                 `protobuf:"bytes,4,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Filename      string                 `protobuf:"bytes,6,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType      string                 `protobuf:"bytes,7,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SourcePath    string                 `protobuf:"bytes,8,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGIndexSourceRequest) Reset() {
	*x = RAGIndexSourceRequest{}
	mi := &file_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGIndexSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGIndexSourceRequest) ProtoMessage() {}

func (x *RAGIndexSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGIndexSourceRequest.ProtoReflect.Descriptor instead.
func (*RAGIndexSourceRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{0}
}

func (x *RAGIndexSourceRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *RAGIndexSourceRequest) GetCharacterDir() string {
	if x != nil {
		return x.CharacterDir
	}
	return ""
}

func (x *RAGIndexSourceRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *RAGIndexSourceRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *RAGIndexSourceRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RAGIndexSourceRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *RAGIndexSourceRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *RAGIndexSourceRequest) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

type RAGIndexSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkCount    int32                  `protobuf:"varint,1,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGIndexSourceResponse) Reset() {
	*x = RAGIndexSourceResponse{}
	mi := &file_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGIndexSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGIndexSourceResponse) ProtoMessage() {}

func (x *RAGIndexSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGIndexSourceResponse.ProtoReflect.Descriptor instead.
func (*RAGIndexSourceResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{1}
}

func (x *RAGIndexSourceResponse) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

type RAGDeleteSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	CharacterDir  string                 `protobuf:"bytes,2,opt,name=character_dir,json=characterDir,proto3" json:"character_dir,omitempty"`
	SourceId      string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGDeleteSourceRequest) Reset() {
	*x = RAGDeleteSourceRequest{}
	mi := &file_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGDeleteSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGDeleteSourceRequest) ProtoMessage() {}

func (x *RAGDeleteSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGDeleteSourceRequest.ProtoReflect.Descriptor instead.
func (*RAGDeleteSourceRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{2}
}

func (x *RAGDeleteSourceRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *RAGDeleteSourceRequest) GetCharacterDir() string {
	if x != nil {
		return x.CharacterDir
	}
	return ""
}

func (x *RAGDeleteSourceRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type RAGDeleteSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGDeleteSourceResponse) Reset() {
	*x = RAGDeleteSourceResponse{}
	mi := &file_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGDeleteSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGDeleteSourceResponse) ProtoMessage() {}

func (x *RAGDeleteSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGDeleteSourceResponse.ProtoReflect.Descriptor instead.
func (*RAGDeleteSourceResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{3}
}

func (x *RAGDeleteSourceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RAGSearchRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CharacterId     string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	CharacterDir    string                 `protobuf:"bytes,2,opt,name=character_dir,json=characterDir,proto3" json:"character_dir,omitempty"`
	Query           string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	TopK            int32                  `protobuf:"varint,4,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	MaxContextChars int32                  `protobuf:"varint,5,opt,name=max_context_chars,json=maxContextChars,proto3" json:"max_context_chars,omitempty"`
	MinScore        float32                `protobuf:"fixed32,6,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RAGSearchRequest) Reset() {
	*x = RAGSearchRequest{}
	mi := &file_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGSearchRequest) ProtoMessage() {}

func (x *RAGSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGSearchRequest.ProtoReflect.Descriptor instead.
func (*RAGSearchRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{4}
}

func (x *RAGSearchRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *RAGSearchRequest) GetCharacterDir() string {
	if x != nil {
		return x.CharacterDir
	}
	return ""
}

func (x *RAGSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RAGSearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *RAGSearchRequest) GetMaxContextChars() int32 {
	if x != nil {
		return x.MaxContextChars
	}
	return 0
}

func (x *RAGSearchRequest) GetMinScore() float32 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

type RAGSearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	SourceType    string                 `protobuf:"bytes,2,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Filename      string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Score         float32                `protobuf:"fixed32,6,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGSearchResult) Reset() {
	*x = RAGSearchResult{}
	mi := &file_rag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGSearchResult) ProtoMessage() {}

func (x *RAGSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGSearchResult.ProtoReflect.Descriptor instead.
func (*RAGSearchResult) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{5}
}

func (x *RAGSearchResult) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *RAGSearchResult) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *RAGSearchResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RAGSearchResult) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *RAGSearchResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RAGSearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type RAGSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*RAGSearchResult     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGSearchResponse) Reset() {
	*x = RAGSearchResponse{}
	mi := &file_rag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGSearchResponse) ProtoMessage() {}

func (x *RAGSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGSearchResponse.ProtoReflect.Descriptor instead.
func (*RAGSearchResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{6}
}

func (x *RAGSearchResponse) GetResults() []*RAGSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_rag_proto protoreflect.FileDescriptor

const file_rag_proto_rawDesc = "" +
	"\n" +
	"\trag.proto\x12\n" +
	"cyberverse\"\x8d\x02\n" +
	"\x15RAGIndexSourceRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12#\n" +
	"\rcharacter_dir\x18\x02 \x01(\tR\fcharacterDir\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x1f\n" +
	"\vsource_type\x18\x04 \x01(\tR\n" +
	"sourceType\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x1a\n" +
	"\bfilename\x18\x06 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\a \x01(\tR\bmimeType\x12\x1f\n" +
	"\vsource_path\x18\b \x01(\tR\n" +
	"sourcePath\"9\n" +
	"\x16RAGIndexSourceResponse\x12\x1f\n" +
	"\vchunk_count\x18\x01 \x01(\x05R\n" +
	"chunkCount\"}\n" +
	"\x16RAGDeleteSourceRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12#\n" +
	"\rcharacter_dir\x18\x02 \x01(\tR\fcharacterDir\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\"3\n" +
	"\x17RAGDeleteSourceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xce\x01\n" +
	"\x10RAGSearchRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12#\n" +
	"\rcharacter_dir\x18\x02 \x01(\tR\fcharacterDir\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x04 \x01(\x05R\x04topK\x12*\n" +
	"\x11max_context_chars\x18\x05 \x01(\x05R\x0fmaxContextChars\x12\x1b\n" +
	"\tmin_score\x18\x06 \x01(\x02R\bminScore\"\xb1\x01\n" +
	"\x0fRAGSearchResult\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1f\n" +
	"\vsource_type\x18\x02 \x01(\tR\n" +
	"sourceType\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x02R\x05score\"J\n" +
	"\x11RAGSearchResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.cyberverse.RAGSearchResultR\aresults2\x82\x02\n" +
	"\n" +
	"RAGService\x12T\n" +
	"\vIndexSource\x12!.cyberverse.RAGIndexSourceRequest\x1a\".cyberverse.RAGIndexSourceResponse\x12W\n" +
	"\fDeleteSource\x12\".cyberverse.RAGDeleteSourceRequest\x1a#.cyberverse.RAGDeleteSourceResponse\x12E\n" +
	"\x06Search\x12\x1c.cyberverse.RAGSearchRequest\x1a\x1d.cyberverse.RAGSearchResponseB*Z(github.com/cyberverse/server/internal/pbb\x06proto3"

var (
	file_rag_proto_rawDescOnce sync.Once
	file_rag_proto_rawDescData []byte
)

func file_rag_proto_rawDescGZIP() []byte {
	file_rag_proto_rawDescOnce.Do(func() {
		file_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_proto_rawDesc), len(file_rag_proto_rawDesc)))
	})
	return file_rag_proto_rawDescData
}

var file_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rag_proto_goTypes = []any{
	(*RAGIndexSourceRequest)(nil),   // 0: cyberverse.RAGIndexSourceRequest
	(*RAGIndexSourceResponse)(nil),  // 1: cyberverse.RAGIndexSourceResponse
	(*RAGDeleteSourceRequest)(nil),  // 2: cyberverse.RAGDeleteSourceRequest
	(*RAGDeleteSourceResponse)(nil), // 3: cyberverse.RAGDeleteSourceResponse
	(*RAGSearchRequest)(nil),        // 4: cyberverse.RAGSearchRequest
	(*RAGSearchResult)(nil),         // 5: cyberverse.RAGSearchResult
	(*RAGSearchResponse)(nil),       // 6: cyberverse.RAGSearchResponse
}
var file_rag_proto_depIdxs = []int32{
	5, // 0: cyberverse.RAGSearchResponse.results:type_name -> cyberverse.RAGSearchResult
	0, // 1: cyberverse.RAGService.IndexSource:input_type -> cyberverse.RAGIndexSourceRequest
	2, // 2: cyberverse.RAGService.DeleteSource:input_type -> cyberverse.RAGDeleteSourceRequest
	4, // 3: cyberverse.RAGService.Search:input_type -> cyberverse.RAGSearchRequest
	1, // 4: cyberverse.RAGService.IndexSource:output_type -> cyberverse.RAGIndexSourceResponse
	3, // 5: cyberverse.RAGService.DeleteSource:output_type -> cyberverse.RAGDeleteSourceResponse
	6, // 6: cyberverse.RAGService.Search:output_type -> cyberverse.RAGSearchResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rag_proto_init() }
func file_rag_proto_init() {
	if File_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_proto_rawDesc), len(file_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_proto_goTypes,
		DependencyIndexes: file_rag_proto_depIdxs,
		MessageInfos:      file_rag_proto_msgTypes,
	}.Build()
	File_rag_proto = out.File
	file_rag_proto_goTypes = nil
	file_rag_proto_depIdxs = nil
}
