// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: rag.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RAGService_IndexSource_FullMethodName  = "/cyberverse.RAGService/IndexSource"
	RAGService_DeleteSource_FullMethodName = "/cyberverse.RAGService/DeleteSource"
	RAGService_Search_FullMethodName       = "/cyberverse.RAGService/Search"
)

// RAGServiceClient is the client API for RAGService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RAGServiceClient interface {
	IndexSource(ctx context.Context, in *RAGIndexSourceRequest, opts ...grpc.CallOption) (*RAGIndexSourceResponse, error)
	DeleteSource(ctx context.Context, in *RAGDeleteSourceRequest, opts ...grpc.CallOption) (*RAGDeleteSourceResponse, error)
	Search(ctx context.Context, in *RAGSearchRequest, opts ...grpc.CallOption) (*RAGSearchResponse, error)
}

type rAGServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRAGServiceClient(cc grpc.ClientConnInterface) RAGServiceClient {
	return &rAGServiceClient{cc}
}

func (c *rAGServiceClient) IndexSource(ctx context.Context, in *RAGIndexSourceRequest, opts ...grpc.CallOption) (*RAGIndexSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RAGIndexSourceResponse)
	err := c.cc.Invoke(ctx, RAGService_IndexSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rAGServiceClient) DeleteSource(ctx context.Context, in *RAGDeleteSourceRequest, opts ...grpc.CallOption) (*RAGDeleteSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RAGDeleteSourceResponse)
	err := c.cc.Invoke(ctx, RAGService_DeleteSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rAGServiceClient) Search(ctx context.Context, in *RAGSearchRequest, opts ...grpc.CallOption) (*RAGSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RAGSearchResponse)
	err := c.cc.Invoke(ctx, RAGService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RAGServiceServer is the server API for RAGService service.
// All implementations must embed UnimplementedRAGServiceServer
// for forward compatibility.
type RAGServiceServer interface {
	IndexSource(context.Context, *RAGIndexSourceRequest) (*RAGIndexSourceResponse, error)
	DeleteSource(context.Context, *RAGDeleteSourceRequest) (*RAGDeleteSourceResponse, error)
	Search(context.Context, *RAGSearchRequest) (*RAGSearchResponse, error)
	mustEmbedUnimplementedRAGServiceServer()
}

// UnimplementedRAGServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRAGServiceServer struct{}

func (UnimplementedRAGServiceServer) IndexSource(context.Context, *RAGIndexSourceRequest) (*RAGIndexSourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexSource not implemented")
}
func (UnimplementedRAGServiceServer) DeleteSource(context.Context, *RAGDeleteSourceRequest) (*RAGDeleteSourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSource not implemented")
}
func (UnimplementedRAGServiceServer) Search(context.Context, *RAGSearchRequest) (*RAGSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedRAGServiceServer) mustEmbedUnimplementedRAGServiceServer() {}
func (UnimplementedRAGServiceServer) testEmbeddedByValue()                    {}

// UnsafeRAGServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RAGServiceServer will
// result in compilation errors.
type UnsafeRAGServiceServer interface {
	mustEmbedUnimplementedRAGServiceServer()
}

func RegisterRAGServiceServer(s grpc.ServiceRegistrar, srv RAGServiceServer) {
	// If the following call panics, it indicates UnimplementedRAGServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RAGService_ServiceDesc, srv)
}

func _RAGService_IndexSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RAGIndexSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAGServiceServer).IndexSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAGService_IndexSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAGServiceServer).IndexSource(ctx, req.(*RAGIndexSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RAGService_DeleteSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RAGDeleteSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAGServiceServer).DeleteSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAGService_DeleteSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAGServiceServer).DeleteSource(ctx, req.(*RAGDeleteSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RAGService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RAGSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAGServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAGService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAGServiceServer).Search(ctx, req.(*RAGSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RAGService_ServiceDesc is the grpc.ServiceDesc for RAGService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RAGService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cyberverse.RAGService",
	HandlerType: (*RAGServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IndexSource",
			Handler:    _RAGService_IndexSource_Handler,
		},
		{
			MethodName: "DeleteSource",
			Handler:    _RAGService_DeleteSource_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _RAGService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rag.proto",
}
